### ISSUE TITLE
doesnt works

### ISSUE THREAD

**Issue by nacho1191** [cappig/steam-workshop-downloader#1]
script doesnt works.
download zips files of 18kb with issues.

**Comment by cappig** [comment]
Can you link the mod or collection you're trying to download.
The script pulls mods from external hosting sites so this is probably an issue on their side.

**Comment by nacho1191** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2781804786
https://steamcommunity.com/sharedfiles/filedetails/?id=2858591409&searchtext=

**Comment by cappig** [comment]
Hey thanks for the report. The issue has been fixed in commit 107fb03. 
Version 0.2 should now be working fine (fingers crossed).

Please do report any new bugs that you encounter!
