### ISSUE TITLE
support Steam  Wallpaper Engine

### ISSUE THREAD

**Issue by KiligFei** [cappig/steam-workshop-downloader#3]
Can you support the download of Steam Workshop wallpaper, thank you

https://steamcommunity.com/sharedfiles/filedetails/?id=2997239055&searchtext=

**Comment by cappig** [comment]
Thanks for the feature request! This script already supports downloading mods for The Wallpaper Engine from [Skymods](https://catalogue.smods.ru/game/wallpaper-engine/). Not all mods are available on there but for example [this wallpaper is](https://steamcommunity.com/workshop/filedetails/?id=2218783279). You can request now mods by clicking the [Request new mods and games](https://goo.gl/forms/tN9yupXisG34Lqkl2) button in the left column.

**Comment by cappig** [comment]
I'm closing this issue for now. Feel free to reopen if you have any more questions.

**Comment by KiligFei** [comment]
thanks
